### ISSUE TITLE
get my code with a deal

### ISSUE THREAD

**Issue by chinh4** [sheepy0125/sniper-bot-python#1]
follow me sheep man!!!!!!!!!!! or you won't get my nonexistant code 🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑

**Comment by sheepy0125** [comment]
Next time I see you in real life I will have a chat with you about this issue. See you soon, chinh4thepro.

**Comment by chinh4** [comment]
nooooooooooo
